# Generated by Django 4.1 on 2022-09-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_fees_amount_fees_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
